name: signal_sticker_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/commetchat/signal-sticker-api

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  cryptography: ^2.5.0
  http: ^1.1.0
  protobuf: ^2.1.0
